Command system
theinventors-ftc/ftc-powerplay-teamcode pull request #1
Opened 2023-08-07 06:17 UTC by Agtheo09

Before issuing a pull request, please see the contributing page.

2023-09-24 08:23 UTC, Agtheo09 commented
Merging working command_base branch to master

2023-09-24 08:33 UTC, Agtheo09 commented
@GrBrogremmer09 @alex-bene

2023-09-24 08:41 UTC, GrBrogremmer09 approved these changes

2023-09-24 09:02 UTC, alex-bene requested changes
In total, every file we ended up NOT using should be deleted except the front-slider-related ones we should keep. But, even then, there might be some at places more than on files about the same thing for the front slider (so some should go). The same thing goes for code comments (not explanations -- just code) that we do not use (again with the exception of the front slider).

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/FreightFrenzyAutonomousPlanA_NoOtherSide.java
this file should be deleted

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/FreightFrenzyAutonomousPlanA_NoOtherSide_Inverted.java
this file should be deleted

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PowerPlayTeleOp.java
> +//    }
why is this commented out? Do we have the telemetry subsystem?

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/AprilTagDetectionSubsystemInverted.java
why do we even need this?

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/SlidyRobot.java
whatever code we do not use, please delete it (don't just comment it out).
The only exception would be the front-slider related code which you can just add a note (this is implemented but we ended up not using it for the competitions due to mechanical bugs)

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/AutonomousCommand.java
delete?

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/ElevatorManualCommand.java
if we don't have manual controls, we do not need manual command

2023-09-24 09:02 UTC, alex-bene commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/SimpleAuto.java
the simple auto name here might not be very good

2023-09-24 10:36 UTC, Agtheo09 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PowerPlayTeleOp.java
> +//    }
I created a telemetry subsystem that runs telemetr.update() in the periodic()!

2023-09-24 10:37 UTC, Agtheo09 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/AprilTagDetectionSubsystemInverted.java
I believe that the IDS are different to make different parking positions but @GrBrogremmer09 was in charge of writing this file

2023-09-24 10:38 UTC, Agtheo09 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/ElevatorManualCommand.java
We do have manual controls

2023-09-24 10:43 UTC, Agtheo09 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/AutonomousCommand.java
Yes

2023-09-24 10:46 UTC, Agtheo09 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Slidy_PPV2/commands/SimpleAuto.java
Ok New Name: AutoOneConeCommand

2023-09-24 11:03 UTC, Agtheo09 commented
@alex-bene I resolved every requested changes from you in the next 2 commits after the pull request!

2023-09-24 12:43 UTC, alex-bene commented
@Agtheo09  there are still remaining code-comments that we do not need. Also, let's rename Slidy_PPV2 to just powerplayrobot (or something similar) and slidyrobot to PowerPlayRobot (let's keep the slidy names etc for the notebook and internal use and not the code). Similarly, PPparking.java --> PowerPlayAutonomousParking.java

2023-09-25 11:59 UTC, Agtheo09 commented
@alex-bene I removed(hopefully) all the unnecessary comments and renamed the robot!

2023-09-25 13:54 UTC, alex-bene approved these changes

2023-09-25 13:55 UTC, merged